### ISSUE TITLE
backtracking

### ISSUE THREAD

**Issue by damien-pous** [etiennecallies/click-and-collect#10]
Juste une remarque : quand on s'est trompé et qu'on veut revenir en arrière, ce n'est pas très clair.

- il faut deviner qu'on peut revenir travailler sur le séquent du bas (ou un intermédiaire)
- quand je l'ai fait, j'ai été surpris que ça ne supprime ou mette pas à jour la sous-preuve au dessus dans le cas 'échange'.

C'est sûrement voulu puisque vous utilisez une règle échange implicite, mais bon, il faut peut-être le mentionner qqpart...

**Comment by olaure01** [comment]
Duplicate #8.
