### ISSUE TITLE
[Proof save] Incorrect green background

### ISSUE THREAD

**Issue by olaure01** [etiennecallies/click-and-collect#105]
The background should not be green when importing
https://linearon.modusponens.dev/?s=%281%7C1%29*_%2C+%3F%28%3F1*%3F1%29&p=%2FTd6WFoAAAD%2FEtlBA8CKA9gxIQEMAAAANh7iBeAY1wGCXQA9iIpmlErbapj3kerTnJGvcJLlaehPwTRV5cnJkaq6vxQ1B0gDZR6TyidZHa8mg8DddBpm%2FYb2wJgKFEqHV5n3L9k0yx5hSvzyM6E9pGrOY12j4%2BkaNIHRcZ3UPzA8qK1K%2FVWtNtl6g4UCfGDAWISVDbcV2v%2Bh%2BhKph0IXFpwXn3OE7Hm4vCZoyICLi%2B4yaXTedkGRoCNsgXLaXYPJcY8iULnCd3OpNY1vXXhIShu6ALTmUI2J1F50ka0t0FOEmUppXqJikQqhSAuiUSkIXDL4qH4rtLfVg8zZ5VTlhRzDd%2FSGu3tfX8%2BBrWqDJ3mppQrRbvrROgoOIen4ZvYFE5Y3GbvjcG0qrM1SvCF8QZ7dq24Hy%2BoqYDfcTxzElJHxhMR7qJG0%2FNcCAEivSzMSSPKSZkGGB6m%2BNc2Ub2tPRvHbkPiYxfYetzfxfVbEzbETryJsQdIafrRag7uMwUR4jpNGcVs2iMywX4d1k3XKuIX6i%2BSTze%2FwMuZv%2BGGi7WMwYNONgAAAAAABmgPYMQAA%2BYVB%2FqgACvwCAAAAAABZWg%3D%3D

**Comment by etiennecallies** [comment]
Can't reproduce neither on Chrome neither on Firefox... Have you refresh your cache ?

**Comment by olaure01** [comment]
> Can't reproduce neither on Chrome neither on Firefox... Have you refresh your cache ?

The link was incorrect, could you try with the updated one above?
