### ISSUE TITLE
compilation error: ocsigenserver.ext.ocsipersist-sqlite not found

### ISSUE THREAD

**Issue by lionelvaux** [etiennecallies/click-and-collect#115]
Salut,

By default (at least under Debian 10) `opam install ocsigenserver` does not build `lib/ocsigenserver/extensions/ocsipersist-sqlite.*`.

As a consequence, compiling following the current instructions fails at the following step:
```
ocsigenserver  -c local/etc/click_and_collect/click_and_collect-test.conf
ocsigenserver: ocsigen:main: Fatal - Findlib package ocsigenserver.ext.ocsipersist-sqlite not found: maybe you forgot <findlib path="..."/>?
make: *** [Makefile:58: test.byte] Error 53
```
I have no clue how to tell opam to build the `ocsipersist-sqlite` extension of the `ocsigenserver` package.

**Comment by lionelvaux** [comment]
Installation instructions in PR #117 make this step clear

**Comment by etiennecallies** [comment]
Thanks!
