### ISSUE TITLE
Installation instructions: opam depext ocsigen-start is too greedy

### ISSUE THREAD

**Issue by lionelvaux** [etiennecallies/click-and-collect#116]
Salut,

Current installation instructions suggests to run `opam depext ocsigen-start` to install system dependencies. This is not really a good choice as this forces the installation of `postgresql`, which seems to be the default `ocsipersist` backend for `ocsigen-start` whereas you rely on the `sqlite` backend.

Maybe a finer grained description of dependencies would be better.

**Comment by lionelvaux** [comment]
PR #117 proposes reworked installation instructions that install just what we need

**Comment by etiennecallies** [comment]
Thanks!
