### ISSUE TITLE
cut cut

### ISSUE THREAD

**Issue by lionelvaux** [etiennecallies/click-and-collect#12]
Salut,

**Cut rule.** I wonder if you plan to include the possibility of using the cut rule. For that we would need a dedicated button I guess, and then we could enter the cut formula by clicking on the main connective of an already displayed (sub)formula or by typing something new.

**Cut elimination.** The previous would probably be of little interest without this second feature: do you plan to allow the user to explore cut elimination, for instance by clicking on the cut rule to be eliminated?

Bravo en tout cas,
L.

**Comment by olaure01** [comment]
The current plan is to add a button for activating a 'cut mode'. Once this mode activated, commas will become active symbols and clicking on a comma will ask for a cut formula and apply a cut rule at this place (in a similar way as for tensor). We just have to introduce additional clicking places on the left and on the right of each sequent to take into account cut rules which move the whole context in one premise.

Concerning cut elimination, the main plan is to export to Coq, then use the certified cut-elimination process from [Yalla](https://github.com/olaure01/yalla) inside Coq, and finally import back to click&coLLect.

**Comment by lionelvaux** [comment]
Obviously you already have plans for the future, that will cover some feature requests such as this one. Maybe you could put a roadmap/future work section somewhere in the documentation. (Until I see that I will refrain from asking about quantification.)

About cut elimination: will the interface will yalla allow to perform single cut elimination steps selected by the user (rather than normalization)?

**Comment by olaure01** [comment]
We will consider this roadmap idea. However issues are not such a bad way to follow feature ideas (if you open one about quantifiers, I will answer).

The existing cut-elimination proof in [Yalla](https://github.com/olaure01/yalla) is a big step process. There is current work in defining a small step procedure.
What you are apparently looking for, is more about extending the interface for proof manipulations, while it is currently built for proof constructions, it is quite a different topic.

**Comment by lionelvaux** [comment]
I do not really see the point of implementing the cut rule if we are not able to toy with cut elimination afterwards. Proof manipulations are not obvious to implement in the abstract but if we restrict to concrete examples in the spirit of your reply to #13, cut elimination steps should be straightforward.

I agree that this is not necessarily the purpose of click-and-collect, but would you consider implementing a companion tool? The process would be: we build a closed proof tree with cuts using click-and-collect; when this is done (we reach green) we are allowed to switch to a cut elimination mode where the only thing you can do is to click on cuts to follow a particular cut elimination path (possibly interacting with Yalla).

**Comment by olaure01** [comment]
> I do not really see the point of implementing the cut rule if we are not able to toy with cut elimination afterwards.

You know, sometimes proofs are shorter with cuts...

Concerning moving to a companion tool, this is indeed the right direction I think. We just need to have the associated development task force.

**Comment by olaure01** [comment]
_For future thoughts:_ I see 3 possible scenarios for the Coq export of cut rules (from light and adhoc, to heavy and trusted):
- add `cut_r_ext` as an axiom in `macroll.v`
- extend the `ll` Coq type in `nanoll.v` with a `cut_r` constructor and prove `cut_r_ext` in `macroll.v`
- rely on [Yalla](https://github.com/olaure01/yalla) to get cut as a derivable rule

**Comment by olaure01** [comment]
This feature is under consideration as an [enhancement proposal](https://github.com/etiennecallies/click-and-collect/wiki/Enhancement-Proposals#cut-rule).
