### ISSUE TITLE
The notation feature breaks exports and shareable links

### ISSUE THREAD

**Issue by lionelvaux** [etiennecallies/click-and-collect#121]
Salut,

I have just tested the new notation feature, which is great!  But exporting and shareable links won't work: exporting or visiting the generated link fails with "Technical error, check browser console for more details." as soon as the proof contains the unfolding of a notation.

The only thing that shows up in the browser console is :
```
<!DOCTYPE html>
<!-- Page generated by OCaml with Ocsigen.
See http://ocsigen.org/ and http://caml.inria.fr/ for information -->
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Error 500</title></head><body><h1>Internal Server Error</h1><p>Error 500</p></body></html> proof.js:1072:13
error proof.js:1073:13
Internal Server Error
```

I have checked that this is triggered by unfolding:
* [here](https://linearon.modusponens.dev/?s=a-oa&n=a%2Cb*c&p=%2FTd6WFoAAAD%2FEtlBA8CXAfkCIQEMAAAA7%2BETVeABeACPXQA9iIpmlErbapj3kerTnJGvcJLlaehPwTRV5cnJkZpV9TfGrdJ9SE4ZZFdck5zYw%2B7ePAFGHEg0GPxqO9ZACHZUIrLjOx7ZuCK88lqPv4%2FnJcobDSEnIQ7ZCY7igA6Blps2ZSIssd0SSSMKbY8GAzDIZPsF4gAl%2F8AWyK9Zzi9FPhUq6hwWRFnA5%2BqqjHTDsQAAAAGnAfkCAAB4UcYCqAAK%2FAIAAAAAAFla) is a link to a proof in presence of a notation that is not unfolded: everything is ok
* [here](https://linearon.modusponens.dev/?s=a-oa&n=a%2Cb*c&p=%2FTd6WFoAAAD%2FEtlBA8DJAcgHIQEMAAAAUCuR6eADxwDBXQA9iIpmlErbapj3kerTnJGvcJLlaehPwTRV5cnJkZpV9TfGrdJ9SE4ZZFdck5zYw%2B7ePAFGHEg0GPxqO9ZACHZUIrLjOx7ZuCK88lqPv4%2FnJcobDSEnIQ7ZCY7igA6Blps2ZSIssd0SSSMKbY8GAzDIZPsF4gAl%2F8AWyK9Zzi9FPhWlzmw822oB6uSGy8ryk2PbfPlCofYOojHoDugW71NYZWci3M%2BVCFj8BMZ2xTREK1ksFv0h3%2BlkwU%2BrZsza9jAAAAAAAAAB2QHIBwAA5mCyfagACvwCAAAAAABZWg%3D%3D) is a link to a proof of the same sequent, unfolding the notation: opening this link fails, exporting from the page that generated this link fails too

**Comment by olaure01** [comment]
Note sure this feature is completely ready for testing.

**Comment by etiennecallies** [comment]
Thanks @lionelvaux for testing this feature, but indeed all features are not already working with notations yet.
Proof-sharing should work now (you have to re-share your proof), but export-as-coq, export-as-latex are still under development.
