### ISSUE TITLE
[Provability checks] Empty sequent may be provable with cuts and cyclic notations

### ISSUE THREAD

**Issue by olaure01** [etiennecallies/click-and-collect#139]
The provability check make the turnstile red in: https://click-and-collect.linear-logic.org/?s=&n=a%2C%3Fa%5E
While there is a [proof](https://click-and-collect.linear-logic.org/?s=&n=a%2C%3Fa%5E&p=XQAAgAD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwA9iIoHZADSvL4AO2WnajJ4cSZ3uOM1Jm1oajrUiKOKzW2grfalMe2OncQoTft6Ex%2BQJ9mLBZogq7j6hvb4IvmNar6Gxqzd01To%2BylQexdgI6DWAXMYC0lHyuT5%2B6V1qQIsAc0RTNN6P6n1ksMmvpbnf8wFUIv9nGgUwggZ2AdlAf6yEDNod%2BAhGNhKriTNnfjcF%2FZ%2FMXm0IDhsYSump1U0Fi9fEWZmF6a%2Ferpnw%2BDiI8xKKZW1T1qHdVsWnZGQJMx%2Bs%2Bby%2FX1UrJ%2FFsa0%2FATcJgG%2FHIziSUdYdmLveMcEcdym5UOAo5cO%2B5iL4hmp%2Br3Ry8ZTwrU6IGa6EsBh2o%2F%2Fm0uXn).

**Comment by etiennecallies** [comment]
Good catch! So "because" of cut, if there is any cyclic notation (even not used in current sequent), we just can't determine provability of given sequent. Right?

**Comment by olaure01** [comment]
Indeed, there is probably nothing safe to say regarding provability checks with both cuts and cyclic notations.
