### ISSUE TITLE
[cut elimination] explicit exchange appearing

### ISSUE THREAD

**Issue by olaure01** [etiennecallies/click-and-collect#144]
Clicking on the red cut generates an explicit exchange.
And afterwards, clicking on the green cut generates an error message:
```
"Bad request: invalid proof: Premises conclusion do not match expected premises conclusion after applying rule {\"rule\":\"cut\",\"formula\":{\"type\":\"whynot\",\"value\":{\"type\":\"dual\",\"value\":{\"type\":\"litt\",\"value\":\"o\"}}},\"formulaPosition\":2}}"
```

![cut2](https://user-images.githubusercontent.com/30601497/123524385-2e181480-d6ca-11eb-80e6-7b17cffe1738.png)

**Comment by etiennecallies** [comment]
I cannot reproduce it on https://ccll.linear-logic.org/?s=o&n=o%2C%21o+-o+o&p=XQAAgAD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwA9iIoHZADSvL4AO2WnajJ4cSZ3uOM1Jm1oajsTKyplYJRzl9eyXig67oHQyYTslSub4UdC6wcpw%2BxPIisUM%2FDU96uPUsSW4WGq29bgQWSkZuLsHQNlQSuJJY1%2Fwhv%2Bwj5PBMOfWTPqJjekJ%2F4AbjjPeEld4aqcgmDL6nhNhNMqIK3S%2BdlPrnNUKMTK1Vsa7N6%2BexEUxZNp%2FAVwmpL4geAqFsConAqyJfOE5zu2%2B7nywsFHyyrXVuNV0HZj%2BED0T7kEC6L0Owu72AvFoeqhBXyT1HUNQWuiC7%2FLOjs69F7KAEeB7yyCyqCB3KkOkoHg%2F77Q0PQtVk1%2Fp6GM4Vsp5WILhMteYda%2FeO3Fu1jXAEm8yn4nln1Vtre47leZYwWdvMxfgkqaY3oDB%2BGMKot2N4MY4RBYmvab0HB%2FrEy1RdOXCAqM0NqV2HwwaAR67sHUHFqaExNqRcxlqRzSG3iCLBfm%2FasD5yOuuu3QKr4%2Bcp7uukhnfe6DEg1kX4EaaKPgQfG43SiPeynJjqGakIheNkVqTGI14BnL5A188T9%2FSv7whpBqpJgG6j7Z4iXSI7ZTnJlwrSzDb%2Bo4tWQWnQ2ZE%2BeEKxUB%2F%2Bd2X%2Bw%3D&proof_transformation=1

**Comment by etiennecallies** [comment]
If you used the auto-prover I just pushed a [commit](https://github.com/etiennecallies/click-and-collect/commit/89d9c25fcafc73bc3aec8064defa5cbb0bec277a) that fixes an issue with permutation.

**Comment by olaure01** [comment]
https://ccll.linear-logic.org/?s=o&n=o%2C%21o%E2%8A%B8o&proof_transformation=1&p=XQAAgAD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwA9iIoHZADSvL4AO2WnajJ4cSZ3uOM1Jm1oajsTKyplYJRzl9eyXig67oHQyYTslSub4UdC6wcpw%2BxPIisUM%2FDU96uPUsSW4WGq29bgQWSkZuLsHQNlQSuJJY1%2Fwhv%2Bwj5PBMOfWTPqJjekJ%2F4AbjjPeEld4aqcgmDL6nhNhNMqIK3S%2BdlPrnNUKMTK1Vsa7N6%2BexEUxZNp%2FAVwmpL4geAqFsConAqyJfOE5zu2%2B7nywsFHyyrXVuNV0HZj%2BED0T7kEC6L0Owu72AvFoeqhBXyT1HUNQWuiC7%2FLOjs69F7KAEeB7yyCyqCB3KkOkoHg%2F77Q0PQtVk1%2Fp6GM4Vsp5WILhMteYda%2FeO3Fu1jXAEm8yn4nln1Vtre47leZYwWdvMxffOXicd%2FV3Z6Ir2mMUEliMouw89fZhQVI73bekOs2J2Fadx2bL5bO8cFzjBDe8BB9XfSHwLq%2FSf0mcVfb6SVqlkHvoW5f34Wsk9Jhe3H5Ax8id8j9mlf7KtQsceUe2Lj3rJ%2FHcjKVKtO7GxERnCcyUh4MUOsPTvweR5uAg%2Bgyb97bqGoTrgGMx4aw3MOc8X0cMsW8JJdZFdnlm%2BX6%2Ff6LQ69K%2Fu7tqwBK%2F8HKIJw%3D
