### ISSUE TITLE
highlight cut formula

### ISSUE THREAD

**Issue by lionelvaux** [etiennecallies/click-and-collect#149]
In the proof transformation mode it would be very helpful if the cut formula in each premiss of a cut rule were somehow distinguished (either with a marker, or with a different colour, or a typographic hint).

Otherwise, due to implicit exchanges it becomes quite difficult to track which is cut againts which.

**Comment by etiennecallies** [comment]
Available on [preprod](https://ccll.linear-logic.org/?s=%21%28o-oo%29-o%28o-oo%29&p=XQAAgAD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwA9iIoHZADSvL4AO2WnajJ4cSZ3uOM1Jm1oajsTKyplYJSCC8%2FPl15o2cdBQSb4YZPyNXMmY%2BYVrby5aHtURBgNPK3HM099U6xWmCXBffEMQ92Opy868f1UsRVAwhq8u99x9Ipx2MChm4w3sb88%2Bjer%2FoAa7QQXl660NOjuLxfxXI%2F%2FLGQvHTCTb6qJIJ1Ovyqr841PsheVZ3FE22GLxVikUBr6xbQJGQiikYKD%2FTdJ2JryaBTNMXiAS0YSK7AIdFY98bcL%2FswanQQ1dTedyM8MMxqTED7ksycNqRzPj9adKpk1h3Zhu9L8sjOITnzz4SiCG16h3riovXhQ53m%2BmMc1njSI1O0J5fZjDe3nyDJvE%2BXmNksjaDze%2FFUbuD8hKt1whTZC2RUS23pnLkzGSkOYynmUwb0keckG0DrBVq79uiAthxyIcTV10JB8fKddzCAZV2iS7QMEMN273rJSKCevPeyddwb%2F5qezI4WD4otiAYSfXHaUeiKBbGRDr1ZXU5mwuSOF1KpEXgM%2FJfIe6K4tillpvjfRs7ADviX%2F9T8l6ClIm2JVVzbPh3oNWaurH4uK6pJKCp0DenMXXX3xKbUZ6XKBeaWW7yIRN4Fby4xsgHAdI2uwh%2FaTrQ7X%2F7w8Iww%3D&proof_transformation=1) if you want to test @lionelvaux

**Comment by lionelvaux** [comment]
Parfait!
