### ISSUE TITLE
Linear Implication is Left-Associative 

### ISSUE THREAD

**Issue by GhyselenAlexis** [etiennecallies/click-and-collect#17]
It seems to me that in the automatic translation of formulas, linear implication is assumed left-associative, (for example on the judgment |- A -o A -o A -o A ). I do not know if it is a bug or a feature, but I would have expected right-associativity.

**Comment by olaure01** [comment]
It should definitely be right-associative.

**Comment by etiennecallies** [comment]
Done. I let left-precedence for tensor, par, with, plus, but it's just a one-line change to make it right-precedence: https://github.com/etiennecallies/click-and-collect/blob/master/ll_parser.mly#L20
