### ISSUE TITLE
Activate horizontal sliding

### ISSUE THREAD

**Issue by olaure01** [etiennecallies/click-and-collect#47]
When proofs become large, one can rely on the vertical slider to move but not on an horizontal one.
Looking for a solution might also address the question of navigating inside proofs on mobile phones.

**Comment by etiennecallies** [comment]
There is now an horizontal scroll bar on large proof, for example: https://linearon.modusponens.dev/?s=%E2%8A%A2+%3F%28A%7CA%29%2C+%3F%28B%7CB%7CB%29%2C+%3F%28A%5E%E2%85%8BB%5E%29%2C+%3F%28%E2%8A%A5%E2%8A%97%E2%8A%A5%29&auto_reverse=1
