### ISSUE TITLE
Auto-apply weakening rules

### ISSUE THREAD

**Issue by olaure01** [etiennecallies/click-and-collect#60]
As an option: propose to activate an auto-weakening mode which accepts `1` rule in a `?` context or axiom rule in a `?` context.

**Comment by olaure01** [comment]
After practice, it happens there are (at least) two possible behaviors for auto-weak:
- current one: request for a one rule (by click on 1) or for an axiom rule (by click on turnstile or atom) works even in a ? context
- turnstile only: click on 1 or on atom only strictly accepts the one rule or atomic axiom rule, and click on turnstile requests a more general axiom rule (arbitrary duals (not just atomic), ? context if auto-weak)

I am not sure which choice is the best in practice (somehow I thought about the second one, but I have coded the first one, which proves it is not clear in my mind).

**Comment by etiennecallies** [comment]
You mean that we won't need an auto-weak option ? Click on turnstile would always try axiom, one, in autoweak mode ?

I like the second one.

**Comment by olaure01** [comment]
If we move to the second one, I would suggest:
- click on turnstile generates a dedicated rule request `AxiomGen` or whatever
- if auto-weak mode is off, it only calls axiom rule with arbitrary formula, if auto-weak is on it calls all 0-ary rules extended with ? context

And then maybe the name `auto-weak` is not the best. `extended axioms`?

**Comment by etiennecallies** [comment]
When auto-weak is off, I don't see why it is necessary to differentiate rule request Axiom from rule request AxiomGen. If there is an atom (or its dual) you can click on, there is no different behavior between Axiom and AxiomGen.

My opinion: I would always enable "auto-weak" option on turnstile and hide the button. I think it is clearer and clearer in our interface that when you click on turnstile you trigger magic things. You don't necessarily want to bother the user with too many different shades of magic, given that we would have:
- click on formula or connector (strict `axiom`, strict `one`, strict rules ...) -> _no magic._
- one click on turnstile (general `axiom` OR general `axiom` with ? context OR `one` with ? context) -> _medium magic._
- double click on turnstile (auto prover) -> _high magic._

**Comment by olaure01** [comment]
I mostly agree. Just two points:
- so do you agree that we need two rule requests (at least in presence of auto-weak) so that  `⊢ X, X^, ?A` cannot be solved by single click on `X`?
- the most common presentation of LL relies on the following axiom rule `⊢ A, A^` (for `A` an arbitrary formula). This could thus be natural, in the learning process, to have a setting where exactly this rule can be applied.

**Comment by etiennecallies** [comment]
> * so do you agree that we need two rule requests (at least in presence of auto-weak) so that  `⊢ X, X^, ?A` cannot be solved by single click on `X`?
Yes, single click on `X` would trigger apply_rule with Axiom. Click on turnstile will trigger another method generalized_axiom, that will try to apply Axiom, Axiom with some Weakenings before, One, One  with some Weakenings before, ...

> * the most common presentation of LL relies on the following axiom rule `⊢ A, A^` (for `A` an arbitrary formula). This could thus be natural, in the learning process, to have a setting where exactly this rule can be applied.
Ok I implement the boolean. Let's display the option as a first step. Let's have a further discussion about learning process.

**Comment by etiennecallies** [comment]
Auto-weak is called on double-click on thesis sign, as first attempt to auto-prove sequent.
