### ISSUE TITLE
General axiom in auto-reverse mode with open hypotheses

### ISSUE THREAD

**Issue by olaure01** [etiennecallies/click-and-collect#68]
In auto-reverse mode, it is not possible to click on turnstile to end a proof of `|- A^, A` with `A` not an atom if there is another open hypothesis.
For example, in the proof of `⊢ ?1, !⊥⊗?1`, after applying the tensor rule, it is not possible to close `⊢ ?1, !⊥` directly.
The generated axiom is automatically unfolded through reversible rules.

**Comment by olaure01** [comment]
Probably the same problem: activating the auto-reverse mode on a closed proof which uses non-atomic axioms, unfolds these axioms possibly generating a non-closed proof.
For example, prove `⊢ ?1, !⊥` by click on turnstile and then activate auto-reverse.

**Comment by olaure01** [comment]
Second problem solved but not first one with `⊢ ?1, !⊥⊗?1`.

**Comment by etiennecallies** [comment]
I fixed only the first issue. Now it should be ok (do not forget to refresh the page).
