### ISSUE TITLE
Turnstile color update

### ISSUE THREAD

**Issue by olaure01** [etiennecallies/click-and-collect#79]
Information about provability could be propagated downwards inside the proof:
- if all premises of a rule are provable, the conclusion is provable
- if a sequent is not provable and above a reversible rule, the conclusion of this rule is not provable

This would in particular allow to avoid the attached situations with a meaningless orange turnstile:
![orange2](https://user-images.githubusercontent.com/30601497/116863654-e82d5b80-ac06-11eb-9bf6-cfc6bcaf7142.png)
![orange1](https://user-images.githubusercontent.com/30601497/116863662-ebc0e280-ac06-11eb-8805-6dac6fae276e.png)

**Comment by etiennecallies** [comment]
Good point!

**Comment by etiennecallies** [comment]
I opened for the red turnstile update https://github.com/etiennecallies/click-and-collect/issues/83
