### ISSUE TITLE
"undo-rule" request

### ISSUE THREAD

**Issue by macclavio** [etiennecallies/click-and-collect#8]
add the possibility to undo a rule (by clicking on the line or on the rule label)

**Comment by olaure01** [comment]
We will try to make it clearer, but at any point you can already go back in a lower part of an ongoing proof and apply another rule. It will clear the part above and apply the new rule.

**Comment by etiennecallies** [comment]
We could also undo a rule by clicking on the rule symbol. What do you think @olaure01 ?

**Comment by olaure01** [comment]
You mean rule name? sure. Or also clicking on the line, no problem.
