### ISSUE TITLE
Sequent is modified by auto-prove

### ISSUE THREAD

**Issue by olaure01** [etiennecallies/click-and-collect#80]
For `⊢ A⊗B, A^⅋B^`, click on `⅋` then double click on `⊢`, turns `⊢ A⊗B, A^, B^` into `⊢ A^, A⊗B, B^`.

**Comment by olaure01** [comment]
After some thought, the best is maybe to always display the "post-exchange" conclusion. It will solve the problem above and only impact the conclusion of tensor rules for which it could even be more natural.

**Comment by etiennecallies** [comment]
I was not sure what you wanted this morning so I chose to display only post-exchange sequent.
1. It's simpler to implement.
2. It displays exactly what you would see if you proved the sequent by yourself.

**Comment by olaure01** [comment]
Sorry "post" depends on the direction...
I meant display the lower part of the exchange rule, at least for the final sequent, and probably more readable (closer to usual paper writing) if applied to all rules.

**Comment by etiennecallies** [comment]
It needs a few adaptations in javascript but it should not be long.

**Comment by etiennecallies** [comment]
Fixed by c542aaf
