### ISSUE TITLE
Save proof

### ISSUE THREAD

**Issue by olaure01** [etiennecallies/click-and-collect#82]
Add a button to save the current proof, maybe by [encoding json into a compact string](https://github.com/KilledByAPixel/JSONCrush) and provide an url which uses it as an argument to display the proof back.
If json is too verbose, maybe define an ad-hoc compressed representation of proofs or use [marshaling](https://ocaml.org/api/Marshal.html#VALto_string) (possibly on a datatype with minimal required information).

**Comment by etiennecallies** [comment]
I found this tool that compress/uncompress json object very well http://output.jsbin.com/cayuhox with algorithm `lzma`
I tried it with a proof of `⊢ ?(A⅋A), ?(B⅋B⅋B), ?(A^⅋B^), ?(⊥⊗⊥)` (which is one the biggest I saw for the moment) and the result is only 1387 bytes long (1.4% of the total length), therefore can fit in a URL (max ~2000 characters).

**Comment by etiennecallies** [comment]
Can be tested on https://linearon.modusponens.dev/?s=A*A%5E%2CA%7CA%5E+&p=%2FTd6WFoAAAD%2FEtlBA8DgAYoKIQEMAAAAGqe2UOAFCQDYXQA9iIpmlErbapj3kerTnJGvcJLlaehPwTRV5cnJkaq6vxQ1B0gDZR6TyidZHa8mg4JSGg1Lq9MgA9annVs2fUwQzq1Ru4Xmp64FysViqUvsZMCQ0hyBLfJNXuH9eObZE77E9dZQC9uH%2B34SKT5eFTomW5QiyuIHAS49pCD8xK1JFXZn7uuZ95FXov7LLKyq62%2FXPxb6Wz0LAhwg1kyGPhLsyQAQpB%2BfVlAZTYne0mmW5nvNdI44eIZxrAbEDmOEuNxRuqmuTa5lO1W7PHc8vGNyhlyBewKzGwAAAAHwAYoKAAD9N9RkqAAK%2FAIAAAAAAFla
