### ISSUE TITLE
Propagate non-provability through reversible rules

### ISSUE THREAD

**Issue by etiennecallies** [etiennecallies/click-and-collect#83]
When the auto-prover returns non-provable, all conclusions of reversible rules should be marked as non-provable.

Requires: save the reversible information.

**Comment by olaure01** [comment]
This possibly applies to non-provability checks as well.
Doing more than just going down ⅋, &, ⊥, ! is probably meaningless (at least to start): others like context-free tensor rule are quite specific.

**Comment by etiennecallies** [comment]
Ok then it would be not too hard to do it on javascript side.
