### ISSUE TITLE
[auto-prove] No proof found while OK with Wu's prover

### ISSUE THREAD

**Issue by olaure01** [etiennecallies/click-and-collect#90]
Automated prover stops with no proof found after 3s while [Wu's prover](https://github.com/wujuihsuan2016/LL_prover) is answering immediately:
```
⊢ X^⊗X^, X, ?(X^⊗(X⅋X))
```

**Comment by olaure01** [comment]
It might be that after a bad context split in a tensor rule, a non-provable sequent (here `⊢ X^, ?(X^⊗(X⅋X))`) is addressed in which an infinite sequence of calls to  `apply_d2` is run by scanning all possible `max_d2` (-1, -2, etc.).

**Comment by etiennecallies** [comment]
Oh yes, it might be that, let me see...
