### ISSUE TITLE
[auto-prove] pre-prod error on !A ⊢ ?!?A

### ISSUE THREAD

**Issue by olaure01** [etiennecallies/click-and-collect#97]
The auto-prover generates an error message on pre-prod [!A ⊢ ?!?A](https://linearon.modusponens.dev/?s=%21A+%E2%8A%A2+%3F%21%3FA).

**Comment by etiennecallies** [comment]
Thanks @olaure01 ! I forgot to handle promotion properly : we cannot commute weakening if the weakening is on promoted formula.
